version: '3'

services:
  db:
    image: postgres
    container_name: installations-db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Pass123#
    ports:
      - 5432:5432
  web:
    build: .
    container_name: installations-api
    volumes:
      - .:/code
      - ./static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DEBUG=TRUE
      - ALLOWED_HOSTS=localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=installations-db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=Pass123#
      - WORKER_COUNT=3
      - WORKER_CONNECTIONS=500
      - WORKER_TIMEOUT=60
