# Generated by Django 3.1.4 on 2020-12-11 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('installation_request', 'Installation requested'), ('installation_in_progress', 'Installation in progress'), ('installation_complete', 'Installation Complete'), ('installation_rejected', 'Installation Rejected')], max_length=32)),
                ('notes', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.installation')),
            ],
        ),
    ]
