# Generated by Django 3.1.4 on 2020-12-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_installationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='latest_status',
            field=models.CharField(default='installation_request', max_length=32),
        ),
    ]
